const mockTasks = [
    {
        id: 1000001,
        category: "Venue",
        status: "In Progress",
        title: "Finalize Venue Contract",
        dueDate: "2024-08-15",
        owner: "Alice",
        description: "<p>Review and sign the contract with the Grand Conference Center. Pay the initial deposit.</p>",
        budget: "15000.00",
        attachment: null,
        isArchived: false
    },
    {
        id: 1000002,
        category: "Speakers",
        status: "Open",
        title: "Send out Call for Papers (CFP)",
        dueDate: "2024-08-10",
        owner: "Bob",
        description: "<p>Draft and publish the Call for Papers on the event website and social media channels.</p>",
        budget: "100.00",
        attachment: null,
        isArchived: false
    },
    {
        id: 1000003,
        category: "Marketing",
        status: "Done",
        title: "Initial Website Mockup",
        dueDate: "2024-07-28",
        owner: "Charlie",
        description: "<p>Old mockup for the website, has been superseded by the final design.</p>",
        budget: "500.00",
        attachment: null,
        isArchived: true
    },
    {
        id: 1000004,
        category: "Sponsors",
        status: "Open",
        title: "Create Sponsorship Tiers",
        dueDate: "2024-08-05",
        owner: "Alice",
        description: "<p>Define benefits for Gold, Silver, and Bronze sponsorship packages.</p>",
        budget: "0.00",
        attachment: null,
        isArchived: false
    },
    {
        id: 1000005,
        category: "Logistics",
        status: "Block",
        title: "Order Name Badges",
        dueDate: "2024-08-20",
        owner: "Diana",
        description: "<p>Blocked, waiting for final attendee list from registration platform.</p>",
        budget: "800.00",
        attachment: null,
        isArchived: false
    },
    // Adding 45 more tasks to reach 50
    { id: 1000006, category: "Marketing", status: "Open", title: "Launch Event Website", dueDate: "2024-09-01", owner: "Bob", description: "<p>Deploy the final version of the conference website.</p>", budget: "2500", attachment: null, isArchived: false },
    { id: 1000007, category: "Speakers", status: "In Progress", title: "Book Flights for Keynote Speakers", dueDate: "2024-12-31", owner: "Charlie", description: "<p>Coordinate with travel agent to book flights for Dr. Smith and Prof. Jones.</p>", budget: "2000", attachment: null, isArchived: false },
    { id: 1000008, category: "Logistics", status: "Done", title: "Secure A/V Equipment", dueDate: "2024-07-29", owner: "Diana", description: "<p>Contract signed with 'Sound & Vision' for projectors and microphones.</p>", budget: "3500", attachment: null, isArchived: true },
    { id: 1000009, category: "Sponsors", status: "Open", title: "Draft Sponsor Prospectus", dueDate: "2024-08-18", owner: "Alice", description: "<p>Create the document to send to potential sponsors.</p>", budget: "0", attachment: null, isArchived: false },
    { id: 1000010, category: "Marketing", status: "In Progress", title: "Social Media Campaign", dueDate: "2024-08-25", owner: "Eve", description: "<p>Begin daily posts on Twitter and LinkedIn about the event.</p>", budget: "500", attachment: null, isArchived: false },
    { id: 1000011, category: "Logistics", status: "Open", title: "Order Swag (T-shirts, pens)", dueDate: "2024-08-01", owner: "Bob", description: "<p>Get quotes from three different vendors.</p>", budget: "4000", attachment: null, isArchived: false },
    { id: 1000012, category: "Venue", status: "Done", title: "Confirm Catering Menu", dueDate: "2024-07-25", owner: "Alice", description: "<p>Finalized menu choices with the venue catering manager.</p>", budget: "8000", attachment: null, isArchived: false },
    { id: 1000013, category: "Speakers", status: "Open", title: "Review Submitted Papers", dueDate: "2024-09-15", owner: "Frank", description: "<p>Assemble the review committee to evaluate CFP submissions.</p>", budget: "0", attachment: null, isArchived: false },
    { id: 1000014, category: "Marketing", status: "Block", title: "Send First Email Blast", dueDate: "2024-08-22", owner: "Grace", description: "<p>Waiting for final confirmation of the keynote speaker lineup.</p>", budget: "200", attachment: null, isArchived: false },
    { id: 1000015, category: "Logistics", status: "In Progress", title: "Plan Volunteer Schedule", dueDate: "2024-08-04", owner: "Charlie", description: "<p>Create a shift schedule for all on-site volunteers.</p>", budget: "0", attachment: null, isArchived: false },
    { id: 1000016, category: "Sponsors", status: "Open", title: "Identify Potential Gold Sponsors", dueDate: "2024-08-12", owner: "Diana", description: "<p>Research and list 20 potential companies to approach.</p>", budget: "0", attachment: null, isArchived: false },
    { id: 1000017, category: "Venue", status: "Open", title: "Design Room Layouts", dueDate: "2024-08-02", owner: "Eve", description: "<p>Create diagrams for the main hall and breakout rooms.</p>", budget: "150", attachment: null, isArchived: false },
    { id: 1000018, category: "Marketing", status: "Done", title: "Purchase Event Domain Name", dueDate: "2024-07-20", owner: "Frank", description: "<p>awesomeconf.com has been registered.</p>", budget: "15", attachment: null, isArchived: false },
    { id: 1000019, category: "Logistics", status: "In Progress", title: "Set up Registration Desk Plan", dueDate: "2024-08-19", owner: "Alice", description: "<p>Plan for number of staff, laptops, and badge printers needed.</p>", budget: "300", attachment: null, isArchived: false },
    { id: 1000020, category: "Other", status: "Open", title: "Organize After-Party", dueDate: "2024-09-10", owner: "Grace", description: "<p>Research nearby bars or venues for a post-conference social.</p>", budget: "2500", attachment: null, isArchived: false },
    { id: 1000021, category: "Budget", status: "Open", title: "Q3 Financial Report", dueDate: "2024-10-05", owner: "Heidi", description: "<p>Compile all event-related expenses and income for the quarter.</p>", budget: "0", attachment: null, isArchived: false },
    { id: 1000022, category: "Speakers", status: "Open", title: "Collect Speaker Bios & Headshots", dueDate: "2024-08-03", owner: "Bob", description: "<p>Email all confirmed speakers to request materials for the website.</p>", budget: "0", attachment: null, isArchived: false },
    { id: 1000023, category: "Logistics", status: "In Progress", title: "Source Lanyards", dueDate: "2024-08-14", owner: "Ivan", description: "<p>Comparing prices for custom-branded lanyards.</p>", budget: "600", attachment: null, isArchived: false },
    { id: 1000024, category: "Budget", status: "Done", title: "Submit Venue Deposit Invoice", dueDate: "2024-07-29", owner: "Alice", description: "<p>Expense report submitted for the venue deposit.</p>", budget: "0", attachment: null, isArchived: false },
    { id: 1000025, category: "Sponsors", status: "Open", title: "Contact TechCorp Inc.", dueDate: "2024-08-04", owner: "Charlie", description: "<p>Initial outreach call to the marketing department at TechCorp.</p>", budget: "0", attachment: null, isArchived: false },
    { id: 1000026, category: "Marketing", status: "In Progress", title: "Design Website Banners", dueDate: "2024-08-28", owner: "Judy", description: "<p>Create promotional banners for the website and social media.</p>", budget: "400", attachment: null, isArchived: false },
    { id: 1000027, category: "Venue", status: "Open", title: "Plan Wi-Fi Capacity", dueDate: "2024-08-11", owner: "Diana", description: "<p>Consult with venue IT to ensure adequate Wi-Fi for 500 attendees.</p>", budget: "1000", attachment: null, isArchived: false },
    { id: 1000028, category: "Logistics", status: "Block", title: "Set up Ticketing Platform", dueDate: "2024-09-05", owner: "Ivan", description: "<p>Waiting for finance to approve the payment gateway integration.</p>", budget: "300", attachment: null, isArchived: false },
    { id: 1000029, category: "Sponsors", status: "Done", title: "Sign 'Innovate LLC' as Silver Sponsor", dueDate: "2024-07-22", owner: "Eve", description: "<p>Contract signed and invoice sent.</p>", budget: "0", attachment: null, isArchived: false },
    { id: 1000030, category: "Speakers", status: "In Progress", title: "Create Speaker Info Packet", dueDate: "2024-08-08", owner: "Frank", description: "<p>Packet should include schedule, venue map, and contact info.</p>", budget: "50", attachment: null, isArchived: false },
    { id: 1000031, category: "Marketing", status: "Open", title: "Write Press Release", dueDate: "2024-08-24", owner: "Heidi", description: "<p>Announce keynote speakers and early-bird ticket sales.</p>", budget: "150", attachment: null, isArchived: false },
    { id: 1000032, category: "Budget", status: "Done", title: "Pay for Domain Registration", dueDate: "2024-07-26", owner: "Grace", description: "<p>Paid online.</p>", budget: "15", attachment: null, isArchived: false },
    { id: 1000033, category: "Marketing", status: "In Progress", title: "Test Ticketing Checkout Flow", dueDate: "2024-08-16", owner: "Judy", description: "<p>Perform end-to-end test of the ticket purchase process.</p>", budget: "0", attachment: null, isArchived: false },
    { id: 1000034, category: "Logistics", status: "Open", title: "Arrange On-site Signage", dueDate: "2024-08-17", owner: "Ivan", description: "<p>Get quotes for welcome banners, directional signs, and room signs.</p>", budget: "1200", attachment: null, isArchived: false },
    { id: 1000035, category: "Other", status: "Open", title: "Plan Staff & Volunteer Briefing", dueDate: "2024-09-20", owner: "Alice", description: "<p>Schedule a pre-conference meeting for all staff and volunteers.</p>", budget: "100", attachment: null, isArchived: false },
    { id: 1000036, category: "Venue", status: "Open", title: "Coordinate with Security", dueDate: "2024-09-30", owner: "Bob", description: "<p>Discuss entry/exit points and staff requirements with venue security team.</p>", budget: "2000", attachment: null, isArchived: false },
    { id: 1000038, category: "Marketing", status: "Done", title: "Set up Social Media Accounts", dueDate: "2024-07-29", owner: "Diana", description: "<p>Twitter and LinkedIn profiles are live.</p>", budget: "0", attachment: null, isArchived: false },
    { id: 1000039, category: "Speakers", status: "In Progress", title: "Build Conference Schedule", dueDate: "2024-08-26", owner: "Eve", description: "<p>Create the initial draft of the talk schedule in a spreadsheet.</p>", budget: "0", attachment: null, isArchived: false },
    { id: 1000040, category: "Logistics", status: "Open", title: "Research Coffee Break Options", dueDate: "2024-08-06", owner: "Frank", description: "<p>Get catering options for morning and afternoon coffee breaks.</p>", budget: "2500", attachment: null, isArchived: false },
    { id: 1000041, category: "Marketing", status: "Block", title: "Launch Early-Bird Ticket Sales", dueDate: "2024-08-29", owner: "Grace", description: "<p>Waiting for the ticketing platform to be fully configured.</p>", budget: "0", attachment: null, isArchived: false },
    { id: 1000042, category: "Other", status: "Open", title: "Plan Opening Remarks", dueDate: "2024-08-09", owner: "Heidi", description: "<p>Draft the script for the conference opening speech.</p>", budget: "0", attachment: null, isArchived: false },
    { id: 1000043, category: "Logistics", status: "In Progress", title: "Set up Volunteer Registration Form", dueDate: "2024-09-12", owner: "Ivan", description: "<p>Using Google Forms to collect volunteer applications.</p>", budget: "0", attachment: null, isArchived: false },
    { id: 1000044, category: "Budget", status: "Done", title: "Create Budget Tracking Spreadsheet", dueDate: "2024-07-27", owner: "Judy", description: "<p>Google Sheet created and shared with the team.</p>", budget: "0", attachment: null, isArchived: false },
    { id: 1000046, category: "Speakers", status: "Open", title: "Confirm A/V needs for each speaker", dueDate: "2024-08-31", owner: "Bob", description: "<p>Send a survey to all speakers regarding their presentation needs.</p>", budget: "0", attachment: null, isArchived: false },
    { id: 1000047, category: "Venue", status: "In Progress", title: "Arrange Accessibility Ramps", dueDate: "2024-07-30", owner: "Charlie", description: "<p>Working with venue to ensure all areas are wheelchair accessible.</p>", budget: "500", attachment: null, isArchived: false },
    { id: 1000048, category: "Logistics", status: "Done", title: "Team Kick-off Meeting", dueDate: "2024-07-30", owner: "Diana", description: "<p>Initial planning meeting completed.</p>", budget: "0", attachment: null, isArchived: false },
    { id: 1000049, category: "Budget", status: "Open", title: "Apply for City Event Grant", dueDate: "2025-04-15", owner: "Eve", description: "<p>Gather all necessary documents for the grant application.</p>", budget: "0", attachment: null, isArchived: false },
    { id: 1000050, category: "Budget", status: "Open", title: "Finalize Project Budget", dueDate: "2024-08-07", owner: "Alice", description: "<p>Review all estimated costs and create the final master budget.</p>", budget: "0", attachment: null, isArchived: false }
];